/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package branches.fev2.design;

/**
 *
 * @author alvaro.santos
 */
public class Principal extends javax.swing.JFrame {

      /**
       * Creates new form Principal
       */
      public Principal() {
            initComponents();
      }

      /**
       * This method is called from within the constructor to initialize the
       * form. WARNING: Do NOT modify this code. The content of this method is
       * always regenerated by the Form Editor.
       */
      @SuppressWarnings("unchecked")
      // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
      private void initComponents() {

            jPanel1 = new javax.swing.JPanel();
            btnAdd = new javax.swing.JButton();
            btnList = new javax.swing.JButton();
            btnUpdate = new javax.swing.JButton();
            btnRemove = new javax.swing.JButton();
            btnExit = new javax.swing.JButton();
            jLabel3 = new javax.swing.JLabel();
            jLabel1 = new javax.swing.JLabel();
            jLabel2 = new javax.swing.JLabel();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
            setTitle("Starfleet");

            jPanel1.setLayout(null);

            btnAdd.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
            btnAdd.setText("Add");
            jPanel1.add(btnAdd);
            btnAdd.setBounds(10, 670, 250, 26);

            btnList.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
            btnList.setText("List");
            jPanel1.add(btnList);
            btnList.setBounds(260, 670, 250, 26);

            btnUpdate.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
            btnUpdate.setText("Update");
            jPanel1.add(btnUpdate);
            btnUpdate.setBounds(510, 670, 260, 26);

            btnRemove.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
            btnRemove.setText("Remove");
            jPanel1.add(btnRemove);
            btnRemove.setBounds(770, 670, 250, 26);

            btnExit.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
            btnExit.setText("Exit");
            btnExit.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        btnExitActionPerformed(evt);
                  }
            });
            jPanel1.add(btnExit);
            btnExit.setBounds(1020, 670, 250, 26);

            jLabel3.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 10)); // NOI18N
            jLabel3.setForeground(new java.awt.Color(102, 102, 102));
            jLabel3.setText("Álvaro Santos");
            jPanel1.add(jLabel3);
            jLabel3.setBounds(600, 490, 90, 12);

            jLabel1.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
            jLabel1.setForeground(new java.awt.Color(102, 102, 102));
            jLabel1.setText("Starfleet V2");
            jPanel1.add(jLabel1);
            jLabel1.setBounds(580, 470, 140, 21);

            jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/branches/fev2/design/images/background.JPG"))); // NOI18N
            jPanel1.add(jLabel2);
            jLabel2.setBounds(0, -20, 1280, 750);

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                  layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1275, Short.MAX_VALUE)
            );
            layout.setVerticalGroup(
                  layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE)
            );

            pack();
      }// </editor-fold>//GEN-END:initComponents

      private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
            this.setVisible(false);
            this.dispose();
      }//GEN-LAST:event_btnExitActionPerformed

      /**
       * @param args the command line arguments
       */
      public static void main(String args[]) {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
             */
            try {
                  for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                        if ("Nimbus".equals(info.getName())) {
                              javax.swing.UIManager.setLookAndFeel(info.getClassName());
                              break;
                        }
                  }
            } catch (ClassNotFoundException ex) {
                  java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                  java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                  java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                  java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>

            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                  public void run() {
                        new Principal().setVisible(true);
                  }
            });
      }

      // Variables declaration - do not modify//GEN-BEGIN:variables
      private javax.swing.JButton btnAdd;
      private javax.swing.JButton btnExit;
      private javax.swing.JButton btnList;
      private javax.swing.JButton btnRemove;
      private javax.swing.JButton btnUpdate;
      private javax.swing.JLabel jLabel1;
      private javax.swing.JLabel jLabel2;
      private javax.swing.JLabel jLabel3;
      private javax.swing.JPanel jPanel1;
      // End of variables declaration//GEN-END:variables
}
